version: "3.6"
services:
  nn:
    image: centos:hadoop
    container_name: nn
    ports:
      - 50070:50070
      - 8088:8088
    depends_on:
      - dn1
      - dn2
      - dn3
    volumes:
      - ./shared-volume:/shared-volume
    command: tail -f /dev/null
  
  dn1:
    image: centos:hadoop
    container_name: dn1
    volumes:
      - ./shared-volume:/shared-volume
    entrypoint: /shared-volume/entrypoint.sh
    command: tail -f /dev/null
  
  dn2:
    image: centos:hadoop
    container_name: dn2
    volumes:
      - ./shared-volume:/shared-volume
    entrypoint: /shared-volume/entrypoint.sh
    command: tail -f /dev/null

  dn3:
    image: centos:hadoop
    container_name: dn3
    volumes:
      - ./shared-volume:/shared-volume
    entrypoint: /shared-volume/entrypoint.sh
    command: tail -f /dev/null
    
